GET http://localhost:3000/users

###

GET http://localhost:3000/users/65ddafb295750ee1da52850

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "user_name" : "dodashelDor",
    "password" : "dodashelOr" ,
    "userType" : "cash_Register",
    "first_name" : "doda",
    "last_name" : "shelDor",
    "email_address" :"dodashelDor@dodashelOr.com" ,
    "favorites" : "balck coffe" 
}

###

DELETE http://localhost:3000/users/


###

PATCH http://localhost:3000/users/65ddbf5eeae6d5b8ea3bdd12
Content-Type: application/json

{
    "user_name" : "dodashelmaxwell",
    "password" : " "
}
//===============================================================//
###
GET http://localhost:3000/products
###
GET http://localhost:3000/products/65ddafb295750ee1da52850


###

POST http://localhost:3000/products
Content-Type: application/json

{
    "product_name" : "Dortrhttyteryeyertry",
    "product_amount" : "523",
    "product_Category": "shitttt"
}


###
DELETE http://localhost:3000/products/65e0e3118972939b4d7729bf

###

PATCH http://localhost:3000/products/65e0e30a8972939b4d7729bd
Content-Type: application/json

{
    "product_name" : "dodashelmaxwell",
    "pruduct_amount" : "9",
    "product_Category" : "stt"
}
////////////////////////////////////////////////////////////////
###

GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/"add id"

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "order_user_id" : "65ddbf5eeae6d5b8ea3bdd12",
    "products" : "lsifgjbloj,sdgyiuaheioras.sdfgdfbg",
    "product_Category": "shitttt"
}


###
DELETE http://localhost:3000/order/"add_id"

###

PATCH http://localhost:3000/order/65e4dbdab94203197674dc48
Content-Type: application/json

{  
    "products" : [{"fjhgdfg","fsgshfth","adfdsaf"}],
    "craditCard":"312313135453468484",
}
###